<a href="https://colab.research.google.com/github/Solitte/C-_DZ/blob/main/DZ5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
import re

In [107]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [108]:
with open('/content/drive/MyDrive/Colab Notebooks/skazka-o-rybake-i-rybke.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы

In [109]:
text

' Жил старик со своею старухойУ самого синего моряОни жили в ветхой землянкеРовно тридцать лет и три годаСтарик ловил неводом рыбуСтаруха пряла свою пряжуРаз он в море закинул невод Пришел невод с одною тинойОн в другой раз закинул неводПришел невод с травой морскоюВ третий раз закинул он невод Пришел невод с одною рыбкойС непростою рыбкой  золотоюКак взмолится золотая рыбкаГолосом молвит человечьимОтпусти ты старче меня в мореДорогой за себя дам откупОткуплюсь чем только пожелаешьУдивился старик испугалсяОн рыбачил тридцать лет и три годаИ не слыхивал чтоб рыба говорилаОтпустил он рыбку золотуюИ сказал ей ласковое словоБог с тобою золотая рыбкаТвоего мне откупа не надоСтупай себе в синее мореГуляй там себе на просторе Воротился старик ко старухеРассказал ей великое чудоЯ сегодня поймал было рыбкуЗолотую рыбку не простуюПонашему говорила рыбкаДомой в море синее просиласьДорогою ценою откупаласьОткупалась чем только пожелаюНе посмел я взять с нее выкупТак пустил ее в синее мореСтарика с

In [110]:
len(text)

5531

In [111]:
num_characters = 34 #33 буквы + пробел

In [112]:
import keras
from keras.preprocessing.text import Tokenizer

In [113]:
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [114]:
tokenizer.fit_on_texts(text)

In [115]:
print(tokenizer.word_index)

{' ': 1, 'о': 2, 'е': 3, 'а': 4, 'т': 5, 'р': 6, 'с': 7, 'и': 8, 'н': 9, 'л': 10, 'к': 11, 'у': 12, 'в': 13, 'п': 14, 'б': 15, 'м': 16, 'ы': 17, 'д': 18, 'я': 19, 'ь': 20, 'ч': 21, 'й': 22, 'г': 23, 'з': 24, 'х': 25, 'ю': 26, 'ж': 27, 'ш': 28, 'ц': 29, 'щ': 30, 'ф': 31, 'ъ': 32}


In [116]:
inp_chars = 6 #
data = tokenizer.texts_to_matrix(text)

In [117]:
data[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [118]:
n = data.shape[0]-inp_chars
n  #размер обучающего множества

5525

In [119]:
import numpy as np

In [120]:
X = np.array([data[i:i+inp_chars, :] for i in range(n)])
Y = data[inp_chars:] #предсказание следующего символа

In [121]:
len(X)

5525

In [122]:
X[0]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [123]:
Y[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [124]:
from keras.layers import *
from keras.models import Sequential

In [125]:
model = Sequential()
model.add(Input((inp_chars, num_characters)))
model.add(SimpleRNN(500, activation='tanh'))
model.add(Dense(num_characters, activation='softmax'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_4 (SimpleRNN)    (None, 500)               267500    
                                                                 
 dense_5 (Dense)             (None, 34)                17034     
                                                                 
Total params: 284534 (1.09 MB)
Trainable params: 284534 (1.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [126]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
history = model.fit(X, Y, batch_size=32, epochs=50)

Epoch 1/50
173/173 [==============================] - 4s 16ms/step - loss: 2.8444 - accuracy: 0.2157
Epoch 2/50
173/173 [==============================] - 3s 16ms/step - loss: 2.4584 - accuracy: 0.3222
Epoch 3/50
173/173 [==============================] - 3s 16ms/step - loss: 2.3141 - accuracy: 0.3538
Epoch 4/50
173/173 [==============================] - 4s 24ms/step - loss: 2.2087 - accuracy: 0.3768
Epoch 5/50
173/173 [==============================] - 3s 18ms/step - loss: 2.1451 - accuracy: 0.3944
Epoch 6/50
173/173 [==============================] - 3s 16ms/step - loss: 2.1171 - accuracy: 0.3957
Epoch 7/50
173/173 [==============================] - 3s 16ms/step - loss: 2.0838 - accuracy: 0.4071
Epoch 8/50
173/173 [==============================] - 3s 19ms/step - loss: 2.0571 - accuracy: 0.4081
Epoch 9/50
173/173 [==============================] - 4s 23ms/step - loss: 2.0232 - accuracy: 0.4138
Epoch 10/50
173/173 [==============================] - 3s 16ms/step - loss: 2.0084 - accura

In [127]:
def buildPhrase(inp_str, str_len = 50):
  for i in range(str_len):
    x = []
    for j in range(i, i+inp_chars):
      x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

    x = np.array(x)
    inp = x.reshape(1, inp_chars, num_characters)

    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении

    inp_str += d # дописываем строку

  return inp_str

In [128]:
res = buildPhrase("утренн")
print(res)

1/1 [==============================] - 0s 22ms/step
утреннела конешеме вормтоюко бостору воротись поклонолся


# Слова


In [208]:
with open('/content/drive/MyDrive/Colab Notebooks/skazka-o-rybake-i-rybke.txt', 'r', encoding='utf-8') as f:
    texts = f.read()
    texts = texts.replace('\ufeff', '') # убираем первый невидимый символ

In [209]:
maxWordsCount = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»',
                       lower=True, split=' ', char_level=False)
tokenizer.fit_on_texts([texts])

In [210]:
dist = list(tokenizer.word_counts.items())
print(dist[:10])

[('жил', 1), ('старик', 16), ('со', 4), ('своею', 1), ('старухой', 1), ('у', 5), ('самого', 1), ('синего', 1), ('моря', 2), ('они', 1)]


In [211]:
data = tokenizer.texts_to_sequences([texts])

In [212]:
data

[[155,
  7,
  53,
  156,
  157,
  36,
  158,
  159,
  93,
  160,
  161,
  4,
  162,
  94,
  163,
  95,
  96,
  9,
  97,
  98,
  7,
  164,
  165,
  166,
  5,
  167,
  99,
  168,
  71,
  6,
  4,
  11,
  72,
  22,
  73,
  22,
  2,
  100,
  169,
  6,
  4,
  170,
  71,
  72,
  22,
  73,
  22,
  2,
  171,
  74,
  4,
  172,
  71,
  72,
  6,
  22,
  73,
  22,
  2,
  100,
  101,
  2,
  173,
  101,
  174,
  75,
  175,
  18,
  3,
  176,
  177,
  178,
  179,
  14,
  23,
  76,
  4,
  11,
  102,
  54,
  180,
  181,
  182,
  183,
  77,
  103,
  184,
  185,
  7,
  78,
  6,
  186,
  95,
  96,
  9,
  97,
  98,
  9,
  1,
  187,
  104,
  188,
  105,
  189,
  6,
  16,
  19,
  9,
  190,
  12,
  191,
  192,
  193,
  2,
  194,
  18,
  3,
  195,
  20,
  196,
  1,
  197,
  24,
  25,
  4,
  26,
  11,
  198,
  199,
  25,
  10,
  200,
  37,
  7,
  55,
  21,
  201,
  12,
  202,
  203,
  106,
  204,
  205,
  206,
  16,
  19,
  16,
  1,
  207,
  79,
  208,
  105,
  3,
  209,
  4,
  11,
  26,
  210,
  211,
  212,
  10

In [213]:
len(data[0])

950

In [214]:
res = keras.utils.to_categorical(data[0], num_classes=maxWordsCount)
print( res.shape )

(950, 1000)


In [215]:
inp_words = 3
n = res.shape[0]-inp_words

In [216]:
X = np.array([res[i:i+inp_words, :] for i in range(n)])
Y = res[inp_words:]

In [217]:
total_words = len(tokenizer.word_index) + 1

model = Sequential()

model.add(Input((inp_words, maxWordsCount)))
model.add(GRU(256))
model.add(Dense(maxWordsCount, activation='softmax'))
model.summary()

model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_7 (GRU)                 (None, 256)               966144    
                                                                 
 dense_13 (Dense)            (None, 1000)              257000    
                                                                 
Total params: 1223144 (4.67 MB)
Trainable params: 1223144 (4.67 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [218]:
history = model.fit(X, Y, batch_size=32, epochs=50)

Epoch 1/50
30/30 [==============================] - 4s 47ms/step - loss: 6.8635 - accuracy: 0.0612
Epoch 2/50
30/30 [==============================] - 1s 47ms/step - loss: 6.0139 - accuracy: 0.0317
Epoch 3/50
30/30 [==============================] - 1s 30ms/step - loss: 5.4867 - accuracy: 0.0253
Epoch 4/50
30/30 [==============================] - 1s 36ms/step - loss: 5.3278 - accuracy: 0.0454
Epoch 5/50
30/30 [==============================] - 1s 47ms/step - loss: 5.2003 - accuracy: 0.0634
Epoch 6/50
30/30 [==============================] - 1s 45ms/step - loss: 5.0588 - accuracy: 0.0718
Epoch 7/50
30/30 [==============================] - 1s 42ms/step - loss: 4.8605 - accuracy: 0.1235
Epoch 8/50
30/30 [==============================] - 1s 29ms/step - loss: 4.5812 - accuracy: 0.1584
Epoch 9/50
30/30 [==============================] - 1s 29ms/step - loss: 4.2300 - accuracy: 0.2186
Epoch 10/50
30/30 [==============================] - 1s 29ms/step - loss: 3.8533 - accuracy: 0.2672
Epoch 11/

In [219]:
def buildPhrase(texts, str_len=20):
    res = texts
    data = tokenizer.texts_to_sequences([texts])[0]
    for i in range(str_len):
        x = keras.utils.to_categorical(data[i: i + inp_words], num_classes=maxWordsCount)  # преобразуем в One-Hot-encoding
        inp = x.reshape(1, inp_words, maxWordsCount)

        pred = model.predict(inp)
        indx = pred.argmax(axis=1)[0]
        data.append(indx)

        res += " " + tokenizer.index_word[indx]  # дописываем строку

    return res

In [220]:
res = buildPhrase("море старик рыбка")
print(res)

1/1 [==============================] - 0s 22ms/step
море старик рыбка забранила ты ступай простофиля в синее поклонися старика старуха хочу дурачина она царицей не быть владычицей взять чтобы жить выкуп
